/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2pchatapp;

/**
 *
 * @author aditya
 */
import java.awt.Color;
import java.net.*;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class ClientGUI extends javax.swing.JFrame implements WritableGUI{
    String username;
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI(String username) {
        this.username = username;
        initComponents();
        populateFriendList();
        this.setTitle(username+"'s ChatBox");
        this.setLocation(220,180);
        jButton1.setBackground(new Color(255,255,255));
        jButton2.setBackground(new Color(255,255,255));
        jButton3.setBackground(new Color(255,255,255));
        btn_send.setBackground(new Color(255,255,255));
        btn_connect.setBackground(new Color(255,255,255));
        jComboBox1.setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_connect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        text_messsage = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_connect.setForeground(new java.awt.Color(153, 153, 255));
        btn_connect.setText("Refresh Friend List");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 170, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 570, 310));

        text_messsage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_messsage.setForeground(new java.awt.Color(153, 153, 255));
        text_messsage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_messsageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_messsageKeyTyped(evt);
            }
        });
        getContentPane().add(text_messsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 390, 30));

        btn_send.setForeground(new java.awt.Color(153, 153, 255));
        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        getContentPane().add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 74, 30));

        jComboBox1.setForeground(new java.awt.Color(153, 153, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 86, 30));

        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Add Friends");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 111, 30));

        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 90, 30));

        jButton3.setForeground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Group Chat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p2pchatapp/chat_backkk.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        populateFriendList();
    }//GEN-LAST:event_btn_connectActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        String friend_name = (String)jComboBox1.getSelectedItem();
        try {
                Socket socket = new Socket("0.0.0.0",444);
                PrintWriter OUT = new PrintWriter(socket.getOutputStream());
                OUT.println("G\n"+friend_name);
                OUT.flush();
                Scanner IN = new Scanner(socket.getInputStream());
                String ip_address = IN.nextLine();
                if(ip_address.equals("*")){
                    jTextArea1.append(" >> "+friend_name+" is Not Logged In !\n");
                }
                else{
                    jTextArea1.append(" Me : "+text_messsage.getText()+"\n");
                    String port = IN.nextLine();
                    MessageSender sender = new MessageSender(username+" : "+text_messsage.getText(), ip_address, Integer.parseInt(port));
                    sender.start();
                }
                text_messsage.setText("");
                socket.close();
            } catch (IOException ex) {
                Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
    }//GEN-LAST:event_btn_sendActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddFriendGUI addFriendGUI = new AddFriendGUI(this, username);
        addFriendGUI.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
                Socket socket = new Socket("0.0.0.0",444);
                PrintWriter OUT = new PrintWriter(socket.getOutputStream());
                OUT.println("X\n"+username);
                OUT.flush();
                socket.close();
                JOptionPane.showMessageDialog(null, "Goodbye "+username+" !");
                System.exit(0);
            } catch (IOException ex) {
                Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //jTextArea1.setText("");
        GroupChatGUI groupChatGUI = new GroupChatGUI(username);
        groupChatGUI.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void text_messsageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_messsageKeyTyped
        
    }//GEN-LAST:event_text_messsageKeyTyped

    private void text_messsageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_messsageKeyReleased
        int key = evt.getKeyCode();
        if (key == evt.VK_ENTER) {
            btn_send.doClick();
        }
    }//GEN-LAST:event_text_messsageKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connect;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField text_messsage;
    // End of variables declaration//GEN-END:variables

    public void write(String str) {
        jTextArea1.append(str+"\n");
    }
    
    public void populateFriendList(){
        try {
                Socket socket = new Socket("0.0.0.0",444);
                PrintWriter OUT = new PrintWriter(socket.getOutputStream());
                System.out.println("Username : "+username);
                jComboBox1.removeAllItems();
                OUT.println("F\n"+username);
                OUT.flush();
                Scanner IN = new Scanner(socket.getInputStream());
                while(IN.hasNextLine()){
                    jComboBox1.addItem(IN.nextLine());
                }
                socket.close();
            } catch (IOException ex) {
                Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
    }
    
    public void addFriend(String friend_name){
        jComboBox1.addItem(friend_name);
    }   
}
