/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2pchatapp;

import java.awt.Color;
import java.net.*;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author aditya
 */
public class GroupChatGUI extends javax.swing.JFrame implements WritableGUI {

    String username;
    
    public GroupChatGUI(String username) {
        initComponents();
        this.username = username;
        this.setTitle(username+"'s Group Chat");
        this.setLocation(250,180);
        jButton1.setBackground(new Color(255,255,255));
        jButton2.setBackground(new Color(255,255,255));
        jButton3.setBackground(new Color(255,255,255));
        jButton4.setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 49, 556, 313));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 255));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 380, 440, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("SEND");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 380, 99, 40));

        jTextField2.setForeground(new java.awt.Color(153, 153, 255));
        jTextField2.setText("8869");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 16, 45, 20));

        jButton2.setForeground(new java.awt.Color(102, 153, 255));
        jButton2.setText("Connect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 8, 100, 30));

        jButton3.setForeground(new java.awt.Color(102, 153, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 8, 90, 30));

        jButton4.setForeground(new java.awt.Color(102, 153, 255));
        jButton4.setText("Exit Group");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p2pchatapp/chat_backkk.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                Socket socket = new Socket("0.0.0.0",444);
                PrintWriter OUT = new PrintWriter(socket.getOutputStream());
                OUT.println("W\n"+username);
                OUT.flush();
                jTextArea1.append(" Me : "+jTextField1.getText()+"\n");
                Scanner IN = new Scanner(socket.getInputStream());
                while(IN.hasNextLine()){
                    String ip_address = IN.nextLine();
                    String port = IN.nextLine();
                    MessageSender sender = new MessageSender(username+" : "+jTextField1.getText(), ip_address, Integer.parseInt(port));
                    sender.start();
                }
                jTextField1.setText("");
                socket.close();
            } catch (IOException ex) {   
                System.out.println(ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
                Socket socket = new Socket("0.0.0.0",444);
                PrintWriter OUT = new PrintWriter(socket.getOutputStream());
                OUT.println("C\n"+username+"\n"+jTextField2.getText());
                OUT.flush();
                Scanner IN = new Scanner(socket.getInputStream());
                String response = IN.nextLine();
                if(response.equals("*")){
                    JOptionPane.showMessageDialog(null, "Could Not Connect to Group Chat !!");
                }
                else{
                    jButton2.setEnabled(false);
                    jButton1.setEnabled(true);
                    MessageListener listener = new MessageListener(this, Integer.parseInt(jTextField2.getText()));
                    listener.start();
                    while(IN.hasNextLine()){
                        String ip_address = IN.nextLine();
                        String port = IN.nextLine();
                        MessageSender sender = new MessageSender(">> "+username+" has joined", ip_address, Integer.parseInt(port));
                        sender.start();
                    }
                    JOptionPane.showMessageDialog(null, "Welcome to Group Chat !!");
                }
                socket.close();
            } catch (IOException ex) {   
                System.out.println(ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        int key = evt.getKeyCode();
        if (key == evt.VK_ENTER) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
                Socket socket = new Socket("0.0.0.0",444);
                PrintWriter OUT = new PrintWriter(socket.getOutputStream());
                OUT.println("Y\n"+username);
                OUT.flush();
                Scanner IN = new Scanner(socket.getInputStream());
                while(IN.hasNextLine()){
                    String ip_address = IN.nextLine();
                    String port = IN.nextLine();
                    MessageSender sender = new MessageSender(">> "+username+" has left", ip_address, Integer.parseInt(port));
                    sender.start();
                }
                socket.close();
                JOptionPane.showMessageDialog(null, "Left The Group");
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupChatGUI("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void write(String str) {
        jTextArea1.append(str+"\n");
    }
}
